version: '4.32.0'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: flowers-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5431:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  backend:
    build: .
    ports:
      - '3001:3000'
    depends_on:
      - database
    env_file:
      - .env

volumes:
  database:
    name: flowers-store-db
